version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      backend-patch-minor:
        applies-to: version-updates
        update-types: ["minor", "patch"]
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      frontend-patch-minor:
        applies-to: version-updates
        update-types: ["minor", "patch"]
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-patch-minor:
        applies-to: version-updates
        update-types: ["minor", "patch"]
