-- VBCT_LOGIN table
CREATE TABLE VBCT_LOGIN (
    LOGIN_ID VARCHAR(50) PRIMARY KEY,
    LOGIN_NAME VARCHAR(100) NOT NULL,
    LOGIN_PASSWORD VARCHAR(100) NOT NULL,
    FIRST_NAME VARCHAR(100),
    MIDDLE_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    DSGN_ID VARCHAR(50),
    EMAIL_ID VARCHAR(100),
    DOB VARCHAR(20),
    PHONE_NO VARCHAR(20),
    SERVICE_FLG CHAR(1),
    LANG_ID VARCHAR(10),
    CRT_DT TIMESTAMP,
    CRT_USR VARCHAR(50),
    LST_UPD_USR VARCHAR(50),
    LST_UPD_DT TIMESTAMP,
    SERVICE_EXPIRY_DT TIMESTAMP,
    FORGOT_PWD VARCHAR(100),
    FRST_LOGIN_FLG CHAR(1),
    PSWD_EXPIRE_DT TIMESTAMP,
    LST_PSWD_UPD_DT TIMESTAMP,
    LOGIN_STARTTIME TIMESTAMP,
    LOGIN_ENDTIME TIMESTAMP,
    IPADDR VARCHAR(50)
);

-- LOGIN table
CREATE TABLE LOGIN (
    USERNAME VARCHAR(100) PRIMARY KEY,
    PWD VARCHAR(100) NOT NULL,
    ROLE VARCHAR(50) NOT NULL
);

-- STUDENT_INFO table
CREATE TABLE STUDENT_INFO (
    STUDENT_ID INT PRIMARY KEY,
    FNAME VARCHAR(100) NOT NULL,
    LNAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    COUNTRY VARCHAR(100),
    YEAR VARCHAR(4),
    STATUS VARCHAR(20)
);

-- STUDENT_EDUCATION table
CREATE TABLE STUDENT_EDUCATION (
    STU_EDU_ID INT PRIMARY KEY,
    STUDENT_ID INT,
    DEGREE_TYPE VARCHAR(100),
    MAJOR VARCHAR(100),
    UNIVERSITY VARCHAR(200),
    UNIVERSITY_LOCATION VARCHAR(200),
    DEGREE_GPA VARCHAR(10),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_INFO(STUDENT_ID)
);

-- STUDENT_CERTIFICATE table
CREATE TABLE STUDENT_CERTIFICATE (
    CERTIFICATE_ID INT PRIMARY KEY,
    STUDENT_ID INT,
    CERTIFICATE_TITLE VARCHAR(200),
    CERTIFICATE_BODY VARCHAR(200),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_INFO(STUDENT_ID)
);

-- STUDENT_WORK table
CREATE TABLE STUDENT_WORK (
    WORK_ID INT PRIMARY KEY,
    STUDENT_ID INT,
    COMPANY_NAME VARCHAR(200),
    POSITION VARCHAR(200),
    START_DATE DATE,
    END_DATE DATE,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_INFO(STUDENT_ID)
); 